### ISSUE TITLE
Nested composite object serialization

### ISSUE THREAD

**Issue by ambitslix** [niXman/yas#101]
I don't see an example for composed object? Other then serializing each member separately is there a compact way?

struct Foo
{
   int i;
};

struct Bar
{
   string m_s;
    Foo m_foo;
};

...
archive_traits::ocreate(oa, archive_type);
auto o0 = YAS_OBJECT_NVP("Bar", ("s", m_s), ("Foo", m_foo));
oa & o0;

Something like that? I tried to do it but it didn't work.

or does it have to be like this?

auto o0 = YAS_OBJECT_NVP("Bar", ("s", m_s), YAS_OBJECT_NVP("Foo", ("i",m_i)));

**Comment by niXman** [comment]
hi,

it depends on what you need.
but the main way is this:
```cpp

struct Foo
{
    int i;

    template<typename Archive>
    void serialize(Archive &ar) {
        ar & YAS_OBJECT("Foo", i);
    }
};

struct Bar
{
    string m_s;
    Foo m_foo;

    template<typename Archive>
    void serialize(Archive &ar) {
        ar & YAS_OBJECT_NVP("Bar", ("s", m_s), ("foo", m_foo));
    }
};


```

**Comment by ambitslix** [comment]
Thanks niXman, I haven't worked with yas for a while and totally forgot that it needs the have the Foo::clear() member...

**Comment by niXman** [comment]
YAS supports `init()` wrapper, maybe this is what you need?

look at test-case: https://github.com/niXman/yas/blob/master/tests/base/include/wrap_init.hpp

will write an example for it, as well as for `asis()`: https://github.com/niXman/yas/blob/master/tests/base/include/wrap_asis.hpp

**Comment by niXman** [comment]
@ambitslix please close

**Comment by niXman** [comment]
the examples was added: https://github.com/niXman/yas/commit/14b455ab83c15877fe4ba1dd042e72a02e7382e4

**Comment by ambitslix** [comment]
Thanks.
