### ISSUE TITLE
Support for -fno-exceptions ?

### ISSUE THREAD

**Issue by pixelblender** [niXman/yas#105]
Hi,

Thank you for this awesome library. Would it be possible to have yas compiled with -fno-exceptions ? atm it throws compile error
`exception_base.hpp:64:45: error: exception handling disabled, use '-fexceptions' to enable`

**Comment by niXman** [comment]
done: https://github.com/niXman/yas/commit/9df10f2753f51c5f269e98d562624266044cbff5

please close.

**Comment by pixelblender** [comment]
woohoo! thanks!
