### ISSUE TITLE
JSON load issue - whitespace between key and ':' not handled

### ISSUE THREAD

**Issue by wordaligned** [niXman/yas#107]
The example below results in: `Error: ../yas/include\yas/types/utility/object.hpp(162): no expected JSON key`

I think the issue here is caused by the whitespace before the `':'` in the input string, which causes the key to be read as `"x "` and not as `"x"`.

```
#include <iostream>
#include <yas/serialize.hpp>
#include <yas/std_types.hpp>

int main()
{
	try
	{
		int x = 0;
		auto const flags = yas::mem | yas::json;
		std::string const json = "{\"x\" : 42}";
		yas::shared_buffer const buf{json.data(), json.size()};
		yas::load<flags>(buf, YAS_OBJECT_NVP("test", ("x", x)));
	}
	catch (const std::exception& e)
	{
		std::cerr << "Error: " << e.what() << std::endl;
	}
}

```

**Comment by niXman** [comment]
hi,

hmm... will fix it now, thanks!

**Comment by niXman** [comment]
done: https://github.com/niXman/yas/commit/cba47df0a91393d3e9a269792710ab50a9b51375

thank you!

please close.

**Comment by wordaligned** [comment]
Thanks for the quick turn around :-)
