### ISSUE TITLE
Build error when serializing std::variant to JSON

### ISSUE THREAD

**Issue by GIGte** [niXman/yas#108]
`std::size_t` is used in the JSON serialization of `std::variant`. See this line: https://github.com/niXman/yas/blob/cba47df0a91393d3e9a269792710ab50a9b51375/include/yas/types/std/variant.hpp#L129
yas tries to serialize `std::size_t` as `yas::object`, and this fails to build on macOS.
The problem is for both saving and loading.

**Comment by niXman** [comment]
hi,

unfortunately I have no macOS.
so should I just add `#include <cstdint>` ?

**Comment by GIGte** [comment]
`$ clang++ main.cpp -Iyas-master/include -std=c++17`

```c++
#include <yas/serialize.hpp>
#include <yas/std_types.hpp>

int main() {
    std::variant<int> v{0};
    auto buf = yas::save<yas::mem | yas::json>(v);
    
    return 0;
}
```

[errors.txt](https://github.com/niXman/yas/files/7697795/errors.txt)

It works when I replace `std::size_t idx` with `std::uint8_t idx`.

I think this is related to https://github.com/niXman/yas/issues/79#issuecomment-932990242

**Comment by niXman** [comment]
ah, got it! thanks!
will fix it soon!

**Comment by niXman** [comment]
done: https://github.com/niXman/yas/commit/74f631061da84ddbfd8a9b1df6603642c1412bfd

please test and report.

**Comment by GIGte** [comment]
Builds now, thanks!
