### ISSUE TITLE
How can I serialize a structure with more than 64 parameters？

### ISSUE THREAD

**Issue by diamond0209** [niXman/yas#110]
I try to serialize a structure with more than 64 params, and it failed .
I add a YAS_PP_TUPLE_TO_SEQ_65 to fit the params size but it still failed.
Am I missing something please?

PS：
I use the YAS_OBJECT to do the serilization

**Comment by daldegam** [comment]
Check if this can help you: https://github.com/niXman/yas/issues/36#issuecomment-409255072

**Comment by niXman** [comment]
@diamond0209 please close the issue.
