### ISSUE TITLE
Pronounce 

### ISSUE THREAD

**Issue by DarwinRepo** [niXman/yas#126]
I use YAS to build my project, which helps me a lot. I want to promote it to my working group. How to pronounce “YAS”?

**Comment by niXman** [comment]
hello,

thank you for your feedback!

> How to pronounce “YAS”?

just **Y**et **A**nother **S**erialization =)

**Comment by DarwinRepo** [comment]
I use yas to build a RPC frame. You know，yas is easy to use. What i do is ,  if you provide a interfece file, and struct define file, it can be source data to my code-generator. I make it easier to use RPC by no coding. emmm providing interfece file and struct define file is enough. "can you provide me a link to the project so I can add it to the list of projects using YAS?" YES BUT NOT NOW
