### ISSUE TITLE
Describe: A C++14 Reflection Library

### ISSUE THREAD

**Issue by DarwinRepo** [niXman/yas#128]
Could YAS provide the operator like this？
https://www.boost.org/doc/libs/1_81_0/libs/describe/doc/html/describe.html#example_json_rpc

**Comment by DarwinRepo** [comment]
The advantages of serializing to JSON are that it can be parsed by multiple languages, has higher readability, and can more easily express and manipulate data.

**Comment by niXman** [comment]
YAS supports JSON too.
https://github.com/niXman/yas#samples

**Comment by niXman** [comment]
> The advantages of serializing to JSON are that it can be parsed by multiple languages, has higher readability, and can more easily express and manipulate data.

but it is incredibly slow compared to binary serialization.
in highly loaded tasks binary serialization is usually preferred.
