### ISSUE TITLE
Raw Ptr Support

### ISSUE THREAD

**Issue by matunbaman** [niXman/yas#129]
Hi, do you have any plan to support raw ptr， thank you！！

**Comment by niXman** [comment]
hi,

could you give an example of when such a possibility is needed?

**Comment by matunbaman** [comment]
yeah,  I have a struct similar to cv::mat 

`struct SMat{
		uint32_t rows, cols, type, elem_size;
		void *data;
	};`
and I don't know how to serial and deserial it.
Thank you!

**Comment by niXman** [comment]
ah, got it.

then you should use the two separated serializer and deserializer functions:
```cpp
// for save:
SMat smap{...};
auto so = YAS_OBJECT_NVP(nullptr, ("rows", smap.rows), ("cols", smap.cols), ("type", smap.type), ("data", yas::intrusive_buffer(smap.elem_size, smap.data)));
auto buf = yas::save<yas::mem>(so);

smap = SMap{};
yas::shared_buffer data;
auto lo = YAS_OBJECT_NVP(nullptr, ("rows", smap.rows), ("cols", smap.cols), ("type", smap.type), ("data", data));
yas::load<yas::mem>(buf, lo);
smap.elem_size = data.size;
smap.data = data.data.get();
```
(not tested)

but you need to be sure the `data` variable must be alive as long as you use the `smap` variable after deserialization.

**Comment by niXman** [comment]
any progress?

**Comment by matunbaman** [comment]
Yes! It's working, Thank you!!
