### ISSUE TITLE
Unicode \u escape sequence in JSON strings not handled

### ISSUE THREAD

**Issue by wordaligned** [niXman/yas#141]
If I run the following program I get an error: `yas\include\yas/detail/tools/save_load_string.hpp(384): invalid string: '\u'
must be followed by 4 hex digits`
```
#include <string>
#include <iostream>

#include <yas/mem_streams.hpp>
#include <yas/json_iarchive.hpp>
#include <yas/std_types.hpp>

struct Object { std::string name; };

template<typename Archive> void serialize(Archive& ar, Object & o)
{
	ar & YAS_OBJECT_NVP("Object", ("name", o.name));
}

int main()
{
	try
	{
		Object object;
		std::string json = "{\"name\": \"\\u00A0\"}";
		yas::mem_istream is(json.data(), json.size());
		yas::json_iarchive<yas::mem_istream, yas::json> ia(is);
		ia & object;
	}
	catch (std::exception const & e)
	{
		std::cout << "Error: " << e.what() << '\n';
	}
}
```

**Comment by niXman** [comment]
hmm... very strange...

could you please re-test it with non-escaped Unicode string?

**Comment by wordaligned** [comment]
When I run this program I get:

```
Error with \u escapes: yas\include\yas/detail/tools/save_load_string.hpp(384): invalid string: '\u' must be followed by 4 hex digits
unescaped strings work```

----

```
#include <string>
#include <iostream>

#include <yas/mem_streams.hpp>
#include <yas/json_iarchive.hpp>
#include <yas/std_types.hpp>

struct Object { std::string name; };

template<typename Archive> void serialize(Archive& ar, Object & o)
{
	ar & YAS_OBJECT_NVP("Object", ("name", o.name));
}

int main()
{
	try
	{
		Object object;
		std::string json = "{\"name\": \"\\u0040\"}";
		yas::mem_istream is(json.data(), json.size());
		yas::json_iarchive<yas::mem_istream, yas::json> ia(is);
		ia & object;
		std::cout << "\\u escapes work\n";
	}
	catch (std::exception const & e)
	{
		std::cout << "Error with \\u escapes: " << e.what() << '\n';
	}
	try
	{
		Object object;
		std::string json = "{\"name\": \"@\"}";
		yas::mem_istream is(json.data(), json.size());
		yas::json_iarchive<yas::mem_istream, yas::json> ia(is);
		ia & object;
		std::cout << "unescaped strings work\n";
	}
	catch (std::exception const & e)
	{
		std::cout << "Error with no escapes: " << e.what() << '\n';
	}
}
```

**Comment by wordaligned** [comment]
https://github.com/niXman/yas/pull/145 - candidate fix

**Comment by niXman** [comment]
merged.

please re-check and close the issue if fixed.

**Comment by wordaligned** [comment]
I have tested this and it fixes the issue, which I can now close.
I would be grateful if you could make a minor release to make it easier for our package manager (vcpkg) to pick the change up. Thanks
