### ISSUE TITLE
Is deserialization of a class object safe if a new class member is added?

### ISSUE THREAD

**Issue by cpp977** [niXman/yas#143]
It is guaranteed that a class instance will be deserialized correctly from a binary archive file if a member is added after the binary archive was constructed?
Example:
```
struct Foo {                                                                                                                                                                               
    std::vector<bool> b{};                                                                                                                                                             
    std::vector<int> i{};
    double f=0.;
};
template<typename Ar>
void serialize(Ar &ar, Foo &t) {
    ar & YAS_OBJECT_NVP(
        "Foo"
        ,("b", t.b)
        ,("i", t.i)
        ,("f", t.f)
    );
}
int main() {
    constexpr std::size_t flags = yas::file /*IO type*/ | yas::binary; /*IO format*/    

    Foo foo;
    foo.b.resize(2);
    foo.b = {false, true};
    foo.i.resize(3);
    foo.i = {3,4,1};
    foo.f = 4.;
    yas::file_ostream ofs("serialized", /*trunc*/ 1);
    yas::save<flags>(ofs, foo);
}
```
And then some time later the `class Foo` gets a new class member, the serialization function however stays the same.
Can this archive file still be used to construct an instance of the changed `class Foo`, i,e, all the old members will be correct and the new members will be default initialized.
I tested it, with this simple example and it seems to work for any position of the new member.

**Comment by niXman** [comment]
hi,

in this case the only thing that matters is the order and the types listed in `YAS_OBJECT_NVP()`
