### ISSUE TITLE
Enumeration as template argument

### ISSUE THREAD

**Issue by haccel** [niXman/yas#15]
template <typename OS, endian_t ET = as_host>
    struct binary_oarchive

It's not handy to make a forward declaration for this class. It's not crtitcal issue, but type bool (instead enum) or removing this argument from template ( may be use it as runtime argument) will be more portable.

**Comment by niXman** [comment]
In this case, I would have to check this flag, and it would reduce the speed of serialization.

If you need to choose endianness at run-time, you can do it like this:
```cpp
template<typename T>
yas::shared_buffer save(T &v, bool as_little) {
   yas::mem_ostream os;
   if ( as_little ) {
      yas::binary_oarchive<yas::mem_ostream, yas::little_endian> oa(os);
      oa & v;
   } else {
      yas::binary_oarchive<yas::mem_ostream, yas::big_endian> oa(os);
      oa & v;
   }
   return os.get_shared_buffer();
}
```
