### ISSUE TITLE
HDF5 file format support for serialization

### ISSUE THREAD

**Issue by uentity** [niXman/yas#19]
Hi!

Do you have any plans to support HDF5 binary format?
HDF5 is portable and well suited to store big scientific data. Serializing to HDF5 would be a huge plus for many purposes.
There was an effort to implement HDF5 support in original boost::serialization, but it seems that purpose is forgotten. Here's the link: https://github.com/dk1978/serialization.git
Maybe you will look into it and estimate if this code can be adopted for YAS?

**Comment by niXman** [comment]
Hi,

> Do you have any plans to support HDF5 binary format?

No.

> Maybe you will look into it and estimate if this code can be adopted for YAS?

Yes, this code can be adopted for YAS excluding the serialization of polymorphic objects, because YAS doesn't support this option.

The problem is I don't have free time to do this...
