### ISSUE TITLE
About macro __cplusplus

### ISSUE THREAD

**Issue by Jin-Whu** [niXman/yas#22]
In Visual Studio 2017 , the macro **__cplusplus** is still 1997, so in **<yas/detail/config/config.hpp>**, check __cplusplus will throw error.

**Comment by Jin-Whu** [comment]
In Visual Studio 2017, this library can be compiled, but can not be used, base d on example test1

**Comment by niXman** [comment]
I have no access to Visual Studio 2017, so patches are welcome :)

**Comment by niXman** [comment]
Done:
https://github.com/niXman/yas/commit/ee248059f7f69c2e94cc73b53aa4de34e0dd90a4

Closed.
