### ISSUE TITLE
The value may be incorrect!

### ISSUE THREAD

**Issue by fonwin** [niXman/yas#27]
Before `is.read()`, must set `v = 0;` first.
https://github.com/niXman/yas/blob/c1698b564bf6950de1b86761b3f5671884253739/include/yas/detail/io/binary_streams.hpp#L245

**Comment by niXman** [comment]
Why the YAS user can't set it?
I think this is a bad idea, to initialize the user variables inside YAS...

**Comment by fonwin** [comment]
I wish this code can be correct:
```
MyObject obj;
ia & obj;
foo(obj);
ia & obj;
bar(obj);
```
But, it must be like this:
```
MyObject obj;
ia & obj;
foo(obj);
obj.clear();
ia & obj;
bar(obj);
```

**Comment by fonwin** [comment]
Because `is.read(&v, std::min<std::size_t>(sizeof(v), ns))` may not fill `v`'s all bytes.

**Comment by niXman** [comment]
I understand what you mean. But I do not agree that need to initialize the variables twice:
```cpp
struct type { std::uint32_t i; std::uint16_t s;};
...
type t{};
ia & t;
```

**Comment by fonwin** [comment]
If the default value is not zero...
```c++
struct type { std::uint32_t i{1234}; std::uint16_t s{5678};};
...
type t{};
ia & t;
```
