### ISSUE TITLE
Boost.Variant support

### ISSUE THREAD

**Issue by arossert** [niXman/yas#29]
Is there any way to use this with [Boost.Variant](http://www.boost.org/doc/libs/1_64_0/doc/html/variant.html)?

**Comment by niXman** [comment]
Support for boost.variant will be published in the next YAS release(6.0.1), probably before the end of this month.

**Comment by arossert** [comment]
Hi, any news regarding the next release?
I’m waiting for the boost variant support.

**Comment by niXman** [comment]
done!

**Comment by niXman** [comment]
test: https://github.com/niXman/yas/blob/master/tests/base/include/boost_variant.hpp

**Comment by arossert** [comment]
Awesome, thanks.
Can you make it as an official release (I can only see up to 5.0.1)?

**Comment by niXman** [comment]
Sorry, but I still have a few fixes so you can use this version for now. Within a few days I will create the 6.0.1 tag.

**Comment by niXman** [comment]
Basically it will be cosmetic fixes.

**Comment by JonathasValeriano** [comment]
Great!!
