### ISSUE TITLE
std::map and c++11 in Xcode

### ISSUE THREAD

**Issue by armadillu** [niXman/yas#35]
Just a little note for anyone having issues with `std::map` on Xcode; I'm finding that to be able to serialize `std::map` in Xcode, I need to bring up the C++ Language Dialect project setting to `C++14 [-std=c++14]`. 

std::vector and other structures I've used so far worked fine in C++11.

**Comment by niXman** [comment]
Hi,

can you show the code sample please?

**Comment by niXman** [comment]
as I can see, this is because xcode`s std::pair has no constexpr constructor:
```
../../ExternalAddons/ofxYas/libs/yas/include/yas/object.hpp:202:9: note: non-constexpr constructor 'pair' cannot be used in a constant expression
        {KVI::first_type::value, KVI::second_type::value}...
        ^

/Applications/Xcode7.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/utility:267:5: note: declared here
    pair(const _T1& __x, const _T2& __y)
    ^
```

**Comment by niXman** [comment]
CLang's `libc++` also provides `constexpr` ctor for `std::pair` in `C++14` and later.

I'll think about fix.

**Comment by niXman** [comment]
fixed in master.

closed.

**Comment by armadillu** [comment]
I can confirm; I can now compile my project using YAS on `std::map` on Xcode using c++11 Language Dialect.

Thanks!
