### ISSUE TITLE
support non-pod struct ?

### ISSUE THREAD

**Issue by sgf** [niXman/yas#40]
support non-pod struct
like this project [troy](https://github.com/wq19901103wq/troy)

**Comment by niXman** [comment]
Hi,

Sorry, but I do not understand your question...

**Comment by sgf** [comment]
how about let yas support  non-pod struct:

```
 std::uint32_t v0 = 444, v1 = 0;
    my_ostream os;
    yas::text_oarchive<my_ostream> oa(os);
    oa & YAS_OBJECT_NVP("object", ("v", v0));
```
to
```
struct myobj{
public:
 std::uint32_t v0;
std::string v1;
}
my_ostream os;
yas::text_oarchive<my_ostream> oa(os);
myobj mo;
mo.v0=444;
mo.v1="txt";
oa.Serialize(mo);

```

**Comment by niXman** [comment]
YAS has always supported the serialization of non-pod structs. You apparently mean something else...

https://github.com/niXman/yas/blob/master/examples/one_memfn/main.cpp

**Comment by sgf** [comment]
```
    // one member-function for save/load
    template<typename Ar>
    void serialize(Ar &ar) {
        ar & YAS_OBJECT_NVP(
            "type"
            ,("i", i)
            ,("d", d)
            ,("s", s)
            ,("v", v)
        );
    }
```
this code is Indispensable ?

**Comment by niXman** [comment]
If you mean the possibility of not enumerating members of structs as in the example you cited - this requires the C++17 support, but YAS must be compatible with C++11 by the end of this year. But next year YAS will switch to using C++14, not C++17.

You can write an adapter yourself that will perform the decomposition of structures.
In pseudocode:
```cpp
template<typename Archive, typename T>
void adapt(Archive &ar, T &&v) {
    if constexpr (num_of_members_in_t(v) == 1) {
        auto&& [v0] = v;
        ar.serialize(v0);
    } else if constexpr (num_of_members_in_t(v) == 2) {
        auto&& [v0, v1] = v;
        ar.serialize(v0, v1);
    }
    .....

}
```

**Comment by niXman** [comment]
https://gist.github.com/utilForever/1a058050b8af3ef46b58bcfa01d5375d

**Comment by sgf** [comment]
my means yas
can be directly call Serialize and Deserialize Styles api without any other code for structs.
just 

```
Serialize(obj)
or
Deserialize(&dobj);
```
and the type of obj support smallest code size.
```
struct
{
just fields.
}
```

**Comment by sgf** [comment]
> If you mean the possibility of not enumerating members of structs as in the example you cited - this requires the C++17 support, but YAS must be compatible with C++11 by the end of this year. But next year YAS will switch to using C++14, not C++17.
> 
> You can write an adapter yourself that will perform the decomposition of structures.
> In pseudocode:
> 
> ```c++
> template<typename Archive, typename T>
> void adapt(Archive &ar, T &&v) {
>     if constexpr (num_of_members_in_t(v) == 1) {
>         auto&& [v0] = v;
>         ar.serialize(v0);
>     } else if constexpr (num_of_members_in_t(v) == 2) {
>         auto&& [v0, v1] = v;
>         ar.serialize(v0, v1);
>     }
>     .....
> 
> }
> ```
Thank you for your patience.
