### ISSUE TITLE
why throw error on save?

### ISSUE THREAD

**Issue by abar52** [niXman/yas#41]
```c++
yas::save<yas::file | yas::binary>( m_glyphdata_bin.c_str(), *this );
terminate called after throwing an instance of 'yas::io_exception'
  what():  /usr/local/include/yas/file_streams.hpp(67): file already exists
```
maybe more intuitive to set save overwrite as default
i have to use undocumented feature to solve it
```c++
    yas::file_ostream ofs( m_glyphdata_bin.c_str(), 1 );
    yas::save<yas::file | yas::binary>( ofs, *this );
```

**Comment by niXman** [comment]
> i have to use undocumented feature to solve it

Why do you say it is not documented?
See public API: https://github.com/niXman/yas/blob/master/include/yas/serialize.hpp#L127

**Comment by niXman** [comment]
> why throw error on save?

Because: `what():  /usr/local/include/yas/file_streams.hpp(67): file already exists`

**Comment by niXman** [comment]
Closed.

**Comment by abar52** [comment]
i just suggest to make yas::file_mode::file_trunc the default mode for the function yas::save<yas::file | yas::binary>(filename,...) it is more consistent with the name of the function then write two lines of codes
cordially.
