### ISSUE TITLE
How can I get the buffer length before really serialize the struct?

### ISSUE THREAD

**Issue by huyuguang** [niXman/yas#43]
for example, the code looks like:

size_t GetPacket(Type const& t, uint8_t* buffer, size_t max_size) {
 if (max_size < get_len_wantted(t)) return 0;
 .....
}

How can I implement the get_len_wantted(t)?

**Comment by niXman** [comment]
Hi,

I plan to implement such an opportunity soon, but now you can get it by implementing the `fake-ostream`.
Please look at https://github.com/niXman/yas/blob/master/include/yas/null_streams.hpp#L52

You should summarize the `size` arg in the `write()` mf, but ignoring the `tptr` arg.
