### ISSUE TITLE
absl::flat_hash_map

### ISSUE THREAD

**Issue by renau** [niXman/yas#54]
Any plan to support absl::flat_hash_map?

Abseil flat hash map is pretty fast and practical for std::string_view.

**Comment by niXman** [comment]
https://github.com/abseil/abseil-cpp/blob/master/absl/container/flat_hash_map.h ?

I think it's worth adding, but at the moment I have no free time...

**Comment by niXman** [comment]
And why not use boost::container::flat_map?

**Comment by renau** [comment]
The abseil library deals much better with c++17 (std::string_view), it is also a bit faster.
Jose Renau
Professor, Computer Science & Engineering
W // http://masc.soe.ucsc.edu

**Comment by askamn** [comment]
Hi @renau 
You can use this to add support for the flat_hash_map. Not sure if this is the correct way, but this is how I made it work (Comments @niXman  ?)

```
#ifndef __yas__types__abseil__absl_flat_map_serializers_hpp
#define __yas__types__abseil__absl_flat_map_serializers_hpp

#include <yas/detail/type_traits/type_traits.hpp>
#include <yas/detail/type_traits/serializer.hpp>
#include <yas/types/concepts/keyval.hpp>

#include <absl/container/flat_hash_map.h>
#include <absl/container/btree_map.h>

namespace yas {
namespace detail {

/***************************************************************************/

template<std::size_t F, typename K, typename V>
struct serializer<
	type_prop::not_a_fundamental,
	ser_case::use_internal_serializer,
	F,
	absl::flat_hash_map<K, V>
> {
	template<typename Archive>
	static Archive& save(Archive &ar, const absl::flat_hash_map<K, V> &map) {
        return concepts::keyval::save<F>(ar, map);
	}

	template<typename Archive>
	static Archive& load(Archive &ar, absl::flat_hash_map<K, V> &map) {
        return concepts::keyval::load<F>(ar, map);
	}
};

/***************************************************************************/

/***************************************************************************/

template<std::size_t F, typename K, typename V>
struct serializer<
	type_prop::not_a_fundamental,
	ser_case::use_internal_serializer,
	F,
	absl::btree_map<K, V>
> {
	template<typename Archive>
	static Archive& save(Archive &ar, const absl::btree_map<K, V> &map) {
        return concepts::keyval::save<F>(ar, map);
	}

	template<typename Archive>
	static Archive& load(Archive &ar, absl::btree_map<K, V> &map) {
        return concepts::keyval::load<F>(ar, map);
	}
};

/***************************************************************************/

} // namespace detail
} // namespace yas

#endif // __yas__types__boost__boost_container_flat_map_serializers_hpp
```

**Comment by niXman** [comment]
@askamn yes, looks OK!
can you please bring it to the appropriate form as others and make PR?

example: https://github.com/niXman/yas/blob/master/include/yas/types/boost/container_map.hpp

and please don't put `absl::btree_map` and `absl::flat_hash_map` together in one file ;)

**Comment by niXman** [comment]
and it is very important to add the test!

you can use this one (https://github.com/niXman/yas/blob/master/tests/base/include/boost_cont_map.hpp) as template.

**Comment by niXman** [comment]
done by https://github.com/niXman/yas/commit/03d158dd3a2fc2012ce6aa37ee4a165ade34fb10
