### ISSUE TITLE
how to use difference function between json serialize with binary serialize?

### ISSUE THREAD

**Issue by huyuguang** [niXman/yas#55]
For example, for some types like big integer (uint256), when serializing to binary, I want just to copy the memory, but when serializing to json, I want to convert it to readable format.
```

template<typename Ar>
void serialize(Ar &ar, uint256_t const& t) {
  std::array<uint8_t, 32> bin = Uint256ToBin(t);
  ar &YAS_OBJECT_NVP("u256", ("", bin));
}

template<typename Ar>
void serialize(Ar &ar, uint256_t const& t) {
  std::string str = Uint256ToStr(t, 10); // base 10
  ar &YAS_OBJECT_NVP("u256", ("", str));
}

```

**Comment by niXman** [comment]
Hi,

cpp```
template<typename Ar>
void serialize(Ar &ar, uint256_t const& t) {
    if ( yas::is_binary_archive<Ar>::value ) {
        std::array<uint8_t, 32> bin = Uint256ToBin(t);
        ar & YAS_OBJECT_NVP("u256", ("", bin));
    } else if ( yas::is_json_archive<Ar>::value ) {
        std::string str = Uint256ToStr(t, 10); // base 10
        ar & YAS_OBJECT_NVP("u256", ("", str));
    } else {
        // unexpected
    }
}

```

**Comment by huyuguang** [comment]
Very thansk!

**Comment by huyuguang** [comment]
The `yas::is_binary_archive<Ar>::value` cannot use for `iarchive`: yas::detail::iarchive_header<65>::type is not static.

I checked the code and found the `oarchive_header::type()` is static , but` iarchive_header::type() `is not, 
and `is_big_endian(), is_little_endian(), compacted(), version()` are static in `oarchive_header` while are not in `iarchive_header`. Maybe it's a typo?

**Comment by huyuguang** [comment]
The yas::is_binary_archive<Ar>::value cannot use for iarchive: yas::detail::iarchive_header<65>::type is not static.

I checked the code and found the `oarchive_header::type()` is static , but `iarchive_header::type()` is not,
and `is_big_endian(), is_little_endian(), compacted(), version()` are static in `oarchive_header `while are not in `iarchive_header`. 

It seems that the header in `oarchive `is built by F, but the header in `iarchive `is read from data.
So what should I do? 
Maybe `if (ar.type() == yas::json) {...} else if (ar.type() == yas.binary) {...}` ?

**Comment by niXman** [comment]
```cpp
template<template<typename Os, std::size_t F> class Ar>
void serialize(Ar &ar, uint256_t const& t) {
    if ( F & yas::binary ) {
        std::array<uint8_t, 32> bin = Uint256ToBin(t);
        ar & YAS_OBJECT_NVP("u256", ("", bin));
    } else if ( F & yas::json ) {
        std::string str = Uint256ToStr(t, 10); // base 10
        ar & YAS_OBJECT_NVP("u256", ("", str));
    } else {
        // unexpected
    }
}
```
Check please. I have no access to compiler right now.

**Comment by huyuguang** [comment]
> ```c++
> template<template<typename Os, std::size_t F> class Ar>
> void serialize(Ar &ar, uint256_t const& t) {
>     if ( F & yas::binary ) {
>         std::array<uint8_t, 32> bin = Uint256ToBin(t);
>         ar & YAS_OBJECT_NVP("u256", ("", bin));
>     } else if ( F & yas::json ) {
>         std::string str = Uint256ToStr(t, 10); // base 10
>         ar & YAS_OBJECT_NVP("u256", ("", str));
>     } else {
>         // unexpected
>     }
> }
> ```
> 
> Check please. I have no access to compiler right now.

The code works when change the first line to 
```
template <template <class, std::size_t> class Ar, class Os, std::size_t F>
void serialize(Ar<Os, F> &ar, uint256_t  &t) {
```

I test `if (ar.type() == yas::binary)`. also works fine.

So, what's the difference?

As my understanding, for `oarchive`, it's the same, but for `iarchive`, it seems some difference exists.
The type is determined in compile time for template type F, relative is determined in runtime for ar.type().
What makes me confused is when the runtime type is different from the compile time? Maybe sometimes we do not know the exact `iarchive` type, so the library determined it in runtime time(read from the data header)? In this situation, what type should use? Could you please provide a sample about it?

**Comment by niXman** [comment]
> The code works when change the first line to
> template <template <class, std::size_t> class Ar, class Os, std::size_t F>

of course)

> Maybe sometimes we do not know the exact iarchive type, so the library determined it in runtime time(read from the data header)?

for `iarchive`s YAS will check the type of archive in template parameter and the readed from input data: https://github.com/niXman/yas/blob/master/include/yas/detail/io/header.hpp#L240

> In this situation, what type should use?

I suggest using my version with `if ( F & yas::binary )` and so...,  because it will be resolved by compiler at compile time.

**Comment by huyuguang** [comment]
> > The code works when change the first line to
> > template <template <class, std::size_t> class Ar, class Os, std::size_t F>
> 
> of course)
> 
> > Maybe sometimes we do not know the exact iarchive type, so the library determined it in runtime time(read from the data header)?
> 
> for `iarchive`s YAS will check the type of archive in template parameter and the readed from input data: https://github.com/niXman/yas/blob/master/include/yas/detail/io/header.hpp#L240
> 
> > In this situation, what type should use?
> 
> I suggest using my version with `if ( F & yas::binary )` and so..., because it will be resolved by compiler at compile time.

I got it. Here YAS just check the type of archive and throw an exception if not match.
And `if (F & yas::binary) `is better because here can use `if constexpr` to get better performance.
