### ISSUE TITLE
using fopen_s instead of fopen

### ISSUE THREAD

**Issue by dvfdr43** [niXman/yas#56]
I'm getting following error when including `<yas/serialize.hpp>`:

`
Error	C4996	'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. S
`

IDE: VS2019

**Comment by niXman** [comment]
Hmm... I have never used `_s` family of functions before. Need research...

**Comment by niXman** [comment]
fixed in master: https://github.com/niXman/yas/commit/422f43f391fae3ca065be5150f08cf1484563bf3

can you test please, because I have no access to MSVC compiler?

**Comment by dvfdr43** [comment]
It works! Thanks
