### ISSUE TITLE
A new release?

### ISSUE THREAD

**Issue by hg-zt** [niXman/yas#71]
I've encountered some issues on ARM platform and found I need to add `signed char` to type traits. Then I found the fixes have already been merged (https://github.com/niXman/yas/commit/0622e860ebef0d32208338a6c49a123d62ff5e6d). Would you mind release a new patch version (like 7.0.5) for this?

**Comment by niXman** [comment]
Hi,

I can, but I need little more time because I have other fixes locally. I think no more than a week...

**Comment by niXman** [comment]
ready: https://github.com/niXman/yas/releases/tag/7.0.5
