### ISSUE TITLE
zero copy and seek stream

### ISSUE THREAD

**Issue by ambitslix** [niXman/yas#74]
Hello,

I've looked through the docs and examples and this library fits very well with my needs but I'm not finding an important feature which is to be able to do zero copy serialization and seek inside data out stream. 

I'd like to use preallocated buffer for serialization, and also be able to seek inside this buffer and serialize without dynamic allocation.

Example:
```
    yas::mem_ostream                             os(size); <= preallocated memory
    yas::binary_oarchive<yas::mem_ostream, opts> oa(os);
    oa&                                          Packet{ 1, 2, 3, 4 };
    os.seek(offset); <= seek to some offset in memory
    oa&                                          Packet{ 1, 2, 3, 4 };
    os.clear(); <= Reset to zero offset and memset to zeros
    etc...
```
Is there a way to do this or something to add to the library? 

Thanks, Best
Mark

**Comment by niXman** [comment]
Hi,

about zero copy: YAS inside is zero-copy, but copying occurs in the `mem_ostream` so user can get contiguous array.
if you dont need this feature - you should implement your own `mem out stream` with `write(const void *ptr, std::size_t size)`

and about seeking: no, there is no such possibility but you can easily implement it in your own `mem out stream`. but, can you explain please how do you plan to determine the offset of the position?

**Comment by ambitslix** [comment]
Thank you it makes sense to implement my specialized mem ostream as you said. The reason I need this and the seek is because I'd like to have the following framing layout:

```
[type0][length0][struct0]...[typeX][lengthX][structX]...[typeBinary][length][binary data]...[typeY][lengthY][structY]

//type (uint16_t) is some enum the tells type of struct that follows
//length (uint32_t) points to next type, also tells length of struct
//struct is some serialized complex type or binary data
```
The total length of such encoded tuples is variable. I would like to keep serializing into a preallocated buffer until it's full. I can do this the following way with specialized mem ostream:

Pseudo-code:
```
  constexpr std::size_t opts = yas::binary | yas::noheader;
  yas::mem_ostream                             os;
  yas::binary_oarchive<yas::mem_ostream, opts> oa(os);
  frameoffset = os.getindex(); // gets current offset for later use
  os.skip(sizeof(type)+sizeof(uint32_t)); //SKIPS 6 bytes to make room for framing type+length
  oa & structX; //encode structX
  structoffset = os.getindex(); // gets current offset for later use
  os.seek(frameoffset): //back to frame pos
  oa & {typeX, structoffset-frameoffset}; //encode framing type + length
  os.seek(structoffset); //Now we are back at the tail
  ...etc

```
 
So I'm determining the seek position based on the previously encoded struct and then rewinding to the encode the framing. This layout allows iterating the whole stream without having to actually read each struct when decoding. Especially if there are large chunks of binary data in between struct it's very efficient. I don't know the binary data length inside in advance so it's not possible to know length before encoding since I'm also reading binary data directly (zero-copy). So this allows for true zero copy solution for any data type.

**Comment by niXman** [comment]
Got it.
I think your idea should works!

Thank you for the explanation!

**Comment by ambitslix** [comment]
Hello,

I've ran into some issues related to this topic. It seems that it all works as long as I'm not using yas::compacted. So what I ended up doing is to use both types of archiver compacted for structs and non-compacted for headers because my headers must be the same length regardless of their values. Is there a better way to do this though? Also is it guaranteed that sizeof(uint32_t) = length of non-compacted value? How about for structs? I basically need to know that some sizeof(Mystruct) = encoded bytes. 

Thanks again!

**Comment by niXman** [comment]
> It seems that it all works as long as I'm not using yas::compacted.

right.

> Is there a better way to do this though?

no, just don't use compacted mode.

> Also is it guaranteed that sizeof(uint32_t) = length of non-compacted value?

yes.

> How about for structs? I basically need to know that some sizeof(Mystruct) = encoded bytes.

just summarize the sizeof's of all the members.

**Comment by niXman** [comment]
I'm not sure I understand the problem...

since you form the header after the serialization of the object, does the serialization mode of the object matter if it is compacted or not?

**Comment by ambitslix** [comment]
Yes the problem ends up being the same for compacted and flat which is that the after each header the seek position needs to be adjusted. This is due to the fact that the length of the object isn't known in advance so the maximum length is assumed for the header in all cases. It can be done but I admit it's a bit hackish with the sizeofs seeks, etc. Ideally I think the archiver should be able to be forced to encode special such that the length is guaranteed. This would avoid having to hack and also seek adjustments needed when decoding, and would be a valid stream. This way it's sort of a bastardized stream.

**Comment by ambitslix** [comment]
Actually the method suggested to summarize members doesn't work. I have following:

struct{
enum Type : std::uint16_t
  {}
  Type          m_type;
  std::uint16_t m_flags;
  std::uint32_t m_length;
}

sizeof(m_type) + sizeof(m_flags) + sizeof(m_length) = 8

But when I serialize it it takes 9 bytes. If I use sizeof(struct) = 12 it's good...

**Comment by niXman** [comment]
> after each header the seek position needs to be adjusted.

yes, if you use compacted mode. but if compacted ode is not used, does the problem disappear?

> Ideally I think the archiver should be able to be forced to encode special such that the length is guaranteed.

I have this point in my TODO. stay tuned for new releases.
I think it will do it this way:
```
auto o = YAS_OBJECT("Header", yas::asis(m_type), m_flags, m_length);
```

> But when I serialize it it takes 9 bytes.

very strange... let me re-check...

**Comment by niXman** [comment]
> But when I serialize it it takes 9 bytes.

ah, right!
for serialization enums one additional byte is added to which the `sizeof(typename std::underlying_type<Enum type>::type)` is written.

**Comment by niXman** [comment]
I remembered: this extra byte was added because the `sizeof()` of the same enum on GCC and MSVC was diff.
I’ll check how things are with it now... if this issue doesn't exist now I will stop adding this extra byte in next releases.

**Comment by ambitslix** [comment]
> > after each header the seek position needs to be adjusted.
> 
> yes, if you use compacted mode. but if compacted ode is not used, does the problem disappear?
> 
> > Ideally I think the archiver should be able to be forced to encode special such that the length is guaranteed.
> 
> I have this point in my TODO. stay tuned for new releases.
> I think it will do it this way:
> 
> ```
> auto o = YAS_OBJECT("Header", yas::asis(m_type), m_flags, m_length);
> ```
Yes that would be very nice!
> 
> > But when I serialize it it takes 9 bytes.
> 
> very strange... let me re-check...

**Comment by ambitslix** [comment]
For now I will have to leave extra room for the header. Another question, would the serialization work correctly with dirty memory, in other words does YAS assume all zeros?

**Comment by niXman** [comment]
> would the serialization work correctly with dirty memory

yes, it works.

> in other words does YAS assume all zeros?

no, in non-compacted mode YAS completely overwrites the destination using byte representation of the source vars.

**Comment by niXman** [comment]
> I remembered: this extra byte was added because the sizeof() of the same enum on GCC and MSVC was diff.
> I’ll check how things are with it now... if this issue doesn't exist now I will stop adding this extra byte in next releases.

yes, this additional byte is redundant and will removed in the next major release.

**Comment by ambitslix** [comment]
Thank you for all the help. It will be simple to remove the extra padding from my protocol when the new release comes. It seems yas provides every major function I need after all, although I do need a special stream to encode my protocol and I think the addition of forcing the width on the archiver is an important extension. I spent quite some time trying and benchmarking most of the open source serialization libs and decided on yas. I tried protobuf, capnproto, flatbuffers, nop and yas. I needed fast cross-endian, json-support, c++11 only, zero-copy support. CapNProto came close but I don't think it can support zero-copy in the way I need it, basically seek must be implementable via an interface. I also preferred a pure c++ solution without meta language compiler.

PS: I think there is a potential bug in mem_istream because mem_istream::end points beyond the potentially readable memory, so for example with mem_istream::getch() or mem_istream::peekch() you are reading beyond the accessible region.

Also just curious what is this formula for realloc? (1 + std::sqrt(5)) / 1.5

**Comment by niXman** [comment]
> I think there is a potential bug in mem_istream because mem_istream::end points beyond the potentially readable memory, so for example with mem_istream::getch() or mem_istream::peekch() one may read beyond the accessible region.

you're right!

> Also just curious what is this formula for realloc? (1 + std::sqrt(5)) / 1.5

I'm not sure, but it seems to me I copied this formula from the `std::vector<>`s implementation from the `grow()` private member function.

**Comment by ambitslix** [comment]
One more question related to this. Is there a way to get size of encoded object without actually serializing the object? The only way I see is using null_ostream but even that needs to be changed so the it retains length.

**Comment by niXman** [comment]
At the moment this can only be achieved with null_ostream, but in the future such an opportunity will appear and I have some developments in this direction...

**Comment by ambitslix** [comment]
How do you use null_ostream to achieve this?

**Comment by niXman** [comment]
ah, you right, I am sorry :(
will fix it in the next bugfix release.

**Comment by ambitslix** [comment]
I've ran some "dirty memory" tests  and they fail. Are you sure that the library is safe with dirty memory? I've asked this before and you said yes but I'm afraid there is a sever bug in this case. If an object is not zero initialized when decoding it may end up with corrupted values. For example:
```
struct Foo
{
  template<typename Archive>
  void serialize(Archive& ar)
  {
    auto o = YAS_OBJECT_NVP("Foo", ("v", v));
    ar&  o;
  }
  std::uint16_t v;
};

int main void(){

    std::vector<uint8_t>                        buf(128);
    constexpr std::size_t                       opts = yas::binary | yas::no_header | yas::compacted;
    yas::mem_ostream                             os(buf.data(), buf.size());
    yas::binary_oarchive<yas::mem_ostream, opts> oa(os);
    yas::mem_istream                             is(buf.data(), buf.size());
    yas::binary_iarchive<yas::mem_istream, opts> ia(is);

      f1.v =  std::numeric_limits<std::uint8_t>::max();
      oa& f1;
      f2.v = std::numeric_limits<std::uint16_t>::max();
      ia& f2;  / <==== /HERE f1 = 255 but f2 = 65535 !!!
      assert(f1.v == f2.v);
}

This fails for all basic types and also vectors etc, you name it!
```

**Comment by niXman** [comment]
yes, you asked me this question and I re-read it again.
I'm sorry, but I think at that moment I was sure your question was not about compacted mode...

I remember about this "feature" when using the compacted mode...

**Comment by niXman** [comment]
> This fails for all basic types and **also vectors** etc

can you explain it please?

**Comment by ambitslix** [comment]
Not only compacted mode is affected. If you serialize vector<char> of size zero for example in non-compacted mode, then decode into previously dirty vector you will get corrupted vector.

**Comment by ambitslix** [comment]
> > This fails for all basic types and **also vectors** etc
> 
> are you talking about values of fundamental types stored in vectors? not about incorrect size of vectors and other containers?

Yes, I tested with vector<char>.

**Comment by niXman** [comment]
got it.

I think there is no perfect solution.
if you save the vector with size == 0, what do you think deserializer should do: 1)clear the dest dest vector?, 2)leave it as is?

**Comment by ambitslix** [comment]
Good question...It depends on how one design the API. Currently the API silently expects that all target object are "empty" (zero initialized)  before decoding. YAS is designed for high performance so it's common case that we would like to re-use the same object in a loop and one also expect that regardless of what was in the object it will be over written by decoder. Also in YAS_OBJECT_.. macros we can specifically serialize members, so at least those members we expect to decode correctly regardless of previous value in object members. I think this is consistent expectation with API. The other option is that in the documentation we state that the API **requires**  all object member to be zeroed before decoding. This requires that programmer carefully write decoders such as:

```
void serialize(Archive& ar)
  {
   ...zero init everything...
    auto o = YAS_OBJECT_NVP("Foo", ("v", v));
    ar&  o;
  }
```

Or perhaps we can provide YAS_OBJECT_ZERO... macro flavor that zero init by default?

**Comment by niXman** [comment]
let me think about possible options...

**Comment by niXman** [comment]
@ambitslix I think I will add a function like `init(T &)` that will be used this way:
```
void serialize(Archive& ar)
  {
    auto o = YAS_OBJECT_NVP("Foo", ("v", v), ("x", yas::init(x)));
    ar &  o;
  }
```
that function will do nothing when writing to the archive, but when reading it will initialize fundamental types with the default value `v = T{};` and will call `clear()` for containers and strings.

do you have any thoughts on this?

**Comment by ambitslix** [comment]
That sounds like the best way to do it. I think as long as it remains optional but default to zero initialize everything. So when decoding by default you zero init:

```
void serialize(Archive& ar)
  {
        auto o = YAS_INIT_OBJECT_NVP("Foo", ("v", v), ("x"))); // <= zero init, clear ...
        ar &  o;
  }
```
The old api stays the same and basically use at your own risk:

```
void serialize(Archive& ar)
  {
    auto o = YAS_OBJECT_NVP("Foo", ("v", v), ("x")));
    ar &  o;
  }
```
Then if you want to customize:
```
YAS_OBJECT_NVP("Foo", ("v", v), ("x", yas::init(x)));
```

Do I understand this correctly?

**Comment by niXman** [comment]
yes, right.

I think I need a few days to implement this...

**Comment by niXman** [comment]
@ambitslix done: https://github.com/niXman/yas/commit/766190aeb683a68c3e222d32ebd31f2b2ab09dab

please check and tell me your thoughts.

**Comment by ambitslix** [comment]
Sorry about the late reply, I've been swamped, let me look at this...

**Comment by ambitslix** [comment]
I'm trying this:
```
struct Foo
{
  template<typename Archive>
  void serialize(Archive& ar)
  {
    ar & YAS_OBJECT_NVP("Foo", ("x", yas::asis(x)));
  }
  std::uint16_t x;
};
```

Which works, but but it doesn't like yas::init(x)

```
init.hpp:58:9: error: no matching function for call to ‘yas::binary_oarchive<yas::mem_ostream, 137>::write(const yas::init_wrapper<short unsigned int&>&)’
   58 |         ar.write(v);
```

So this one should be a NOP when encoding I'm guessing. What is the intended function of asis?

**Comment by niXman** [comment]
ah, my bad, sorry.

fixed: https://github.com/niXman/yas/commit/72a6d54555ce01bb5dc9e549ee82e2c2ff903cc9

**Comment by niXman** [comment]
> In my test above asis and init both zeroes with compact mode but the default doesn't? Is that intentional? So dirty mem test fails with default, but one would expect that with asis also?

please explain, I'm not sure I understood you correctly...

**Comment by ambitslix** [comment]
Could you describe what happens with each case? default, asis and init? It's not clear.

**Comment by niXman** [comment]
sorry for the delay.

look at this:
asis: https://github.com/niXman/yas/blob/master/include/yas/types/utility/asis.hpp -> write: https://github.com/niXman/yas/blob/master/include/yas/detail/io/binary_streams.hpp#L69, read: https://github.com/niXman/yas/blob/master/include/yas/detail/io/binary_streams.hpp#L208

init: https://github.com/niXman/yas/blob/master/include/yas/types/utility/init.hpp

**Comment by ambitslix** [comment]
Ok, thanks that makes sense. I'm will check that it calls clear on custom object, but I'm sure it does.

**Comment by niXman** [comment]
@ambitslix any news?

**Comment by ambitslix** [comment]
I've checked and it works correctly in my initial tests, I will report more when I finish the unit tests. Any ideas on getting the size of the serialized data without using NullStream?

**Comment by niXman** [comment]
> Any ideas on getting the size of the serialized data without using NullStream?

yes, I have an idea. but it will not be fast, a lot of things need to be redone...

closed.

**Comment by ambitslix** [comment]
Actually it would be enough if instead of doing a realloc in the stream if there is no more capacity to be able to stop instead.
