### ISSUE TITLE
Question : compile time check that type is serialisable

### ISSUE THREAD

**Issue by pfeatherstone** [niXman/yas#78]
Is it possible to have a compile time check that a type is yas-serialisable?
To be specific, I am looking to do the following:

```
template<typename Object, typename std::enable_if<YAS_SERIALISABLE<Object>::value>::type = 0>
yas::shared_buffer serialise_yas(const Object& obj)
{
return yas::save<yas::mem | yas::binary>(obj);
}

template<typename Object, typename std::enable_if<!YAS_SERIALISABLE<Object>::value>::type = 0>
yas::shared_buffer serialise_yas(const Object& obj)
{
yas::shared_buffer buf;
printf("%s not yas-serialisable\n", typeid(Object).name());
return buf;
}
```

**Comment by niXman** [comment]
Hi,

look at this: https://stackoverflow.com/questions/27590890

so you need to check for the ability to call the `OArchive::serialize(T)`

I will add such a function a bit later...

**Comment by niXman** [comment]
and: https://stackoverflow.com/questions/257288

**Comment by pfeatherstone** [comment]
> Hi,
> 
> look at this: https://stackoverflow.com/questions/27590890
> 
> so you need to check for the ability to call the `OArchive::serialize(T)`
> 
> I will add such a function a bit later...

Presumably I have to substitute OArchive for a specific archive?

**Comment by pfeatherstone** [comment]
Using https://stackoverflow.com/questions/27590890, so far i have

```
template<typename Object, 
         typename std::enable_if<isFunctionCallable<Object>(yas::binary_oarchive<yas::mem_ostream, yas::binary>::serialize)>::type = 0>
yas::shared_buffer serialise_yas(const Object& obj)
{
return yas::save<yas::mem | yas::binary>(obj);
}

template<typename Object, 
         typename std::enable_if<!isFunctionCallable<Object>(yas::binary_oarchive<yas::mem_ostream, yas::binary>::serialize)>::type = 0>
yas::shared_buffer serialise_yas(const Object& obj)
{
yas::shared_buffer buf;
printf("%s not yas-serialisable\n", typeid(Object).name());
return buf;
}
```
But doesn't work. Any help?

**Comment by pfeatherstone** [comment]
Is there a way of doing this using boost hof library ?

**Comment by niXman** [comment]
@pfeatherstone I currently don't have access to a laptop, I will try to answer you later

**Comment by pfeatherstone** [comment]
@niXman Any luck?

**Comment by niXman** [comment]
@pfeatherstone I'm sorry, I'm really very sorry, I completely forgot about it %)

please explain, is this an opportunity you need only for your types?

**Comment by pfeatherstone** [comment]
Ideally it would work for any type.
I basically need functions as described:
```
template<typename Object, typename std::enable_if<YAS_SERIALISABLE<Object>::value>::type = 0>
yas::shared_buffer serialise_yas(const Object& obj)
{
return yas::save<yas::mem | yas::binary>(obj);
}

template<typename Object, typename std::enable_if<!YAS_SERIALISABLE<Object>::value>::type = 0>
yas::shared_buffer serialise_yas(const Object& obj)
{
yas::shared_buffer buf;
printf("%s not yas-serialisable\n", typeid(Object).name());
return buf;
}
```
So templated serialise/deserialise functions for any type that either return true (and serialise/deserialise) if the yas functions exist or false otherwise.

I basically need a runtime error, as opposed to a compile time error.

**Comment by niXman** [comment]
in `master`: https://github.com/niXman/yas/commit/3adf228ec4bc7faed0bbb84a29b36b508c5c2e76
later will be marked as release.

check it please and let me know about this.

example:
```
using Ar = yas::binary_oarchive<yas::mem_ostream>;
static_assert(yas::is_serializable<Ar, std::string>::value, "");

struct nonserializable_type {};
static_assert(!yas::is_serializable<Ar, nonserializable_type>::value, "");

```

**Comment by niXman** [comment]
@pfeatherstone any news?

**Comment by pfeatherstone** [comment]
Sorry for the late reply. Yes the example code you give works. I haven’t had time to try it properly with what I want to do. I’m sure it will work. Thank you. You can close the issue if you want

**Comment by pfeatherstone** [comment]
I quickly tried to substitute your type_trait in the enable_if above and cannot get it to work. That’s a me problem. I’ll look at it next week. Thanks again
