### ISSUE TITLE
Question : when do you plan on supporting msgpack? 

### ISSUE THREAD

**Issue by pfeatherstone** [niXman/yas#80]
Questions:
Do you still plan on supporting msgpack? 
Do you plan on supporting XML?
What in the JSON serialiser is not fully compliant?
There are a few header-only libraries that could help: RapidXML, RapidJSON, msgpack-c

**Comment by pfeatherstone** [comment]
For msgpack, msgpack-c doesn't support as many STL and non-STL containers as you do? To use that, one would probably have to submit a massive pull request supporting these containers:
```
std::array
std::bitset
std::chrono::duration
std::chrono::time_point
std::complex
std::deque
std::forward_list
std::list
std::map
std::multimap
std::multiset
std::optional
std::pair
std::set
std::string
std::string_view
std::tuple
std::unordered_map
std::unordered_multimap
std::unordered_multiset
std::unordered_set
std::variant
std::vector
std::wstring
boost::array
boost::chrono::duration
boost::chrono::time_point
boost::optional
boost::variant
boost::container::deque
boost::container::string
boost::container::wstring
boost::container::vector
boost::container::static_vector
boost::container::stable_vector
boost::container::list
boost::container::slist
boost::container::map
boost::container::multimap
boost::container::set
boost::container::multiset
boost::container::flat_map
boost::container::flat_multimap
boost::container::flat_set
boost::container::flat_multiset
boost::unordered_map
boost::unordered_multimap
boost::unordered_set
boost::unordered_multiset
boost::fusion::pair
boost::fusion::tuple
boost::fusion::vector
boost::fusion::list
boost::fusion::map
boost::fusion::set
yas::intrusive_buffer (only save)
yas::shared_buffer
```
The second difficulty would be getting your nice macro YAS_DEFINE_INTRUSIVE_SERIALIZE to work with msgpack-c

**Comment by niXman** [comment]
> Do you still plan on supporting msgpack?

yes

> Do you plan on supporting XML?

no, but it’s not difficult to implement...

> What in the JSON serialiser is not fully compliant?

the serializer is actually compatible.
it's about a deserializer. you cannot deserialize that JSON whose schema is not described or does not match.

for example:
```
static const char *json = R("{"second":2}");

int first{}, second{};

auto obj = YAS_OBJECT(nullptr, first, second);
yas_deserializer_object & obj; // here you will get an exception that there is no "first" member in JSON;
```

> For msgpack, msgpack-c doesn't support as many STL and non-STL containers as you do?

yes, it does not directly support, but each of the types you listed can be represented as msgpack...


Unfortunately, at the moment I am focusing on YAS refactoring with the goal of implementing something else... this is a lot of work and I do not always have enough time for this... but I try...

**Comment by pfeatherstone** [comment]
Thank you for your response. I'll add one more question here.
I noticed that since yas is header only, you cannot use YAS_DEFINE_INTRUSIVE_SERIALIZE in a cpp file somewhere, then expect yas to serialise your object somewhere in another cpp file. Since the second cpp file has no knowledge of the (de)serialisation functions being defined. I was wondering, there could be a runtime registration of (de)serialisation functions. For example there could be a function registration manager, implemented as a static singleton, which can be called inside YAS_DEFINE_INTRUSIVE_SERIALIZE to register the functions. Then, to serialise or deserialise an object, you use the singleton as a proxy (which should have the functions registered). The only thing you would need is 1 cpp file which defines the singleton. Or you leave it up to the user to define the static singleton somewhere in their application. The rest would be header only as usual. YAS_DEFINE_INTRUSIVE_SERIALIZE would have to be guarded with another MACRO in case it is used in a header file and the header file is included in multiple CPP files. This would avoid the (de)serialisation functions being registered several times. Does this make sense?

**Comment by pfeatherstone** [comment]
I would do this myself in a PR but i'm not very good with the crazy MACRO expansions you do like with YAS_DEFINE_INTRUSIVE_SERIALIZE
