### ISSUE TITLE
Compile warning in Android

### ISSUE THREAD

**Issue by CharlesHo110** [niXman/yas#82]
there are some compile warnings in the compiling of Android NDK r17c. such as 
std_streams.hpp 51: explicitly defaulted move assignment oparator is deleted.
std_streams.hpp 45: move assignment operator of "std_ostream_adapter" is implicitly deleted because field 'os' is of reference type 'std::ostream &'

**Comment by niXman** [comment]
yes, it is a known warning. will fixed in the next release.

thanks
