### ISSUE TITLE
boost.multiprecision support.

### ISSUE THREAD

**Issue by danieagle** [niXman/yas#84]
Hi!
There are support in Yas to cpp_int, cpp_dec_float and cpp_rational (from boost.multiprecision)?
If not, can you guide me to add this support ?

From this link [https://www.boost.org/doc/libs/1_74_0/libs/multiprecision/doc/html/boost_multiprecision/tut/serial.html](url) 
this types have boost serialization support, mybe this help.

[]'s Dani.

**Comment by niXman** [comment]
Hi,

> There are support in Yas to cpp_int, cpp_dec_float and cpp_rational (from boost.multiprecision)?

no.

> If not, can you guide me to add this support ?

first I need to look at that implementation...

**Comment by niXman** [comment]
hmm..

the easiest way is to use `boost::multiprecision::number::str()` to save, and to use concrete type constructor using saved string to load.
but I'm sure this is not the most optimal way in terms of performance...

also, in the code of `boost::multiprecision` I found several serialization functions. I need to think...

**Comment by danieagle** [comment]
Thanks! :-)

**Comment by niXman** [comment]
@danieagle sorry, I was on vacation.

your question is still relevant?

**Comment by danieagle** [comment]
Hi! Thanks!

No. :-) I will use boost.serialization. in binary files has lower but acceptable speed and a resonable penalty
for compatibility ^^

beside this, I beliave this is a good thing to add/have in Yas.

Best Wishes, Dani.
