### ISSUE TITLE
Invalid JSON 

### ISSUE THREAD

**Issue by ambitslix** [niXman/yas#86]
Hello,

The following results in an  invalid JSON string:

```
    std::vector<uint8_t>                       buf(MBytes);
    constexpr std::size_t                      opts = yas::json | yas::no_header;
    yas::mem_ostream                           os(buf.data(), buf.size());
    yas::json_oarchive<yas::mem_ostream, opts> oa(os);
    yas::mem_istream                           is(buf.data(), buf.size());
    yas::json_iarchive<yas::mem_istream, opts> ia(is);
    std::map<std::string, std::string>         map({ { "A", "B" }, { "C", "D" } });

    oa& YAS_OBJECT_NVP("obj", ("map", yas::init(map)));

```

```
{"map":{{"key":"A","val":"B"},{"key":"C","val":"D"}}} <<== Invalid JSON
```

Or should it be?

```
{"map":{"A":"B","C":"D"}}
```

Or am I missing something? I read in the docs that the serialization is not JSON compliant so that would explain this. Are you interested in adding a helper function to convert to valid json? For example:

```
std::string yas::toJSON(const std::string& in)
{ 
  std::string validjson;
  ...convert by removing extra "{,},key,value,"...
  return validjson;
}
```

**Comment by niXman** [comment]
Hi,

> Should be?

yes, because yas-object is used as wrapper around key-value pair.
save: https://github.com/niXman/yas/blob/master/include/yas/types/concepts/keyval.hpp#L57
load: https://github.com/niXman/yas/blob/master/include/yas/types/concepts/keyval.hpp#L112

> Are you interested in adding a helper function to convert to valid json?

hmm... I need to think...

**Comment by ambitslix** [comment]
I'm not sure I understand your answer. Is the expected result an invalid JSON?

**Comment by niXman** [comment]
> Is the expected result an invalid JSON?

yes.
but it is wrong to call it "invalid". in terms of syntax - JSON is correct.

maybe it makes sense to change the generation of JSON objects for map's when the key is a string...

**Comment by ambitslix** [comment]
In terms of any JSON RFC the yas generated JSON is invalid, see here for example  (https://jsonformatter.curiousconcept.com/#)

Is the reason for generating an invalid JSON is to identify the type? For example for:

map<int,string> with yas generates:
```
{12:A",45:"B"} <== Invalid JSON
```
This is unambiguous, but it would be valid JSON in quotes like this:

```
{"12":A","45":"B"}
```

So to summarize for map<int,string> and map<string,string> yas JSON serializer generates invalid JSON strings.

**Comment by niXman** [comment]
ah, I read your question inattentively! sorry!

so
> {"map":{{"key":"A","val":"B"},{"key":"C","val":"D"}}} <<== Invalid JSON

yes, is Invalid JSON

**Comment by niXman** [comment]
checking...

**Comment by niXman** [comment]
blocked because: https://github.com/niXman/yas/pull/85#issuecomment-709900591

**Comment by niXman** [comment]
the simplest solution is to make the key-value pairs members of an array:
```
{"map":[{"key":"A","val":"B"},{"key":"C","val":"D"}]}
```
what do you think about this?

**Comment by ambitslix** [comment]
This is fine, however ideally you want to have no key:value notation. It's redundant and takes up space. But perhaps this is necessary for the yas::json parser(archiver) to deserialize properly?

Either way I have written a converter that can remove the key:value notation so it can be used to display pretty json like so:

```
{"map":[{"A":"B"},{"C":"D"}]}
```

Would it be hard to add a function to get this format like opts = yas::json | yas::pretty ?

So this format would not be serializable but it would be valid json and could be converted to yas:json format. So basically the archiver would use key:value notation but for JSON pretty we can do conversion back and forth to yas::json?

Another alternative is this way:
```
    std::vector<uint8_t>                       buf(MBytes);
    constexpr std::size_t                      opts = yas::json | yas::no_header;
    yas::mem_ostream                           os(buf.data(), buf.size());
    yas::json_oarchive<yas::mem_ostream, opts> oa(os);
    yas::mem_istream                           is(buf.data(), buf.size());
    yas::json_iarchive<yas::mem_istream, opts> ia(is);
    std::map<std::string, std::string>         map({ { "A", "B" }, { "C", "D" } });

    oa& YAS_OBJECT_NVP("obj", ("map", yas::init(map)));

   std::string res(buf.begin(), buf.end());

   std::string js = yas::toPrettyJSON(res);     //  <== removes key:value

   std::string yasjs = yas::toYASJSON(js);     //  <== adds key:value back

```

**Comment by niXman** [comment]
I think that doing something wrong in order to correct it later is wrong.
so I would like to find a way to fix the root cause of...

**Comment by niXman** [comment]
so this way looks the simplest:
> {"map":[{"key":"A","val":"B"},{"key":"C","val":"D"}]}

but you're right, ideally I would like to get rid of `key`/`val` entirely...

**Comment by ambitslix** [comment]
As I pointed out  earlier you can just use explicit type:

```
{"type":"int","map":{"12":"AB","23":"AB"}}
```

**Comment by niXman** [comment]
temporarily I did this way:
> {"map":[{"k":"A","v":"B"},{"k":"C","v":"D"}]}

maybe I'll redo it later. I have no free time at the moment, sorry :(

**Comment by niXman** [comment]
https://github.com/niXman/yas/commit/627d9e8d66abfaa6e9558296b007f7536fe0e4da

**Comment by niXman** [comment]
@ambitslix can we close this issue?

**Comment by ambitslix** [comment]
Ok thank you. I will try to look into adding this myself when I get some free time. Let me know if you like my idea.
