### ISSUE TITLE
The problem on the format of save<json>(map)

### ISSUE THREAD

**Issue by mrbeardad** [niXman/yas#93]
# Problem
```cpp
std::map<int, int> map{{1, 1}, {2, 2}, {3, 3}};
std::map<std::string, int> obj{{"a", 1}, {"b", 2}, {"c", 3}};
yas::save<yas::file | yas::json>("file", YAS_OBJECT("obj", map, obj);
std::cout << std::ifstream{"file"}.rdbuf();
// OUTPUT:
// {"map":{{"key":1,"val":1},{"key":2,"val":2},{"key":3,"val":3}},"obj":{{"key":"a","val":1.0},{"key":"b","val":2.0},{"key":"c","val":3.0}}}
//
// Desired OUTPUT:
// {"map":{{"key":1,"val":1},{"key":2,"val":2},{"key":3,"val":3}},"obj":{"a":"1","b":2,"c",3}
```
So it means to specialized for map (and also other map). Is there a available option to get it?

**Comment by niXman** [comment]
Hi,

I'll try to figure it out on the weekend.

thanks.

**Comment by mrbeardad** [comment]
And I found a new problem on `save<json>(map)`  
The right format may be `{"map": [ {"key": 1, "value": 1}, {"key":2, "value":2} ]`  
but not `{"map": { {"key":1,"val":1},{"key":2,"val":2 } }`  
`{ key: value}` means object, and `[ value, value ]` means list.

At last, thank you for your reply. :-}

**Comment by niXman** [comment]
look at this just for info: https://github.com/niXman/yas/issues/86

**Comment by niXman** [comment]
@mrbeardad 

which version are you using?
because as far as I can see the latest version should generate `{"map": [ {"key": 1, "value": 1}, {"key":2, "value":2} ]`

**Comment by niXman** [comment]
with current master branch the result should be: `{"map":[{"k":1,"v":1},{"k":2,"v":2},{"k":3,"v":3}],"obj":[{"k":"a","v":1},{"k":"b","v":2},{"k":"c","v":3}]}`

**Comment by mrbeardad** [comment]
I'm using this version #91 . I have tested it again, it is still `{}` but not `[]`

**Comment by niXman** [comment]
with current master branch the result is this: {"map":[{"k":1,"v":1},{"k":2,"v":2},{"k":3,"v":3}],"obj":[{"k":"a","v":1},{"k":"b","v":2},{"k":"c","v":3}]}

**Comment by mrbeardad** [comment]
emm... I mean #91 is the latest commit on YAS. Is it different from the latest commit on your local repository?

**Comment by niXman** [comment]
> Is it different from the latest commit on your local repository?

looks like yes.

**Comment by niXman** [comment]
please close the ticket.

**Comment by mrbeardad** [comment]
Sorry, do you mean to close this issue? And can I know when you are going to commit it.

**Comment by niXman** [comment]
I do not understand what you expect from me, because I answered above: `with current master branch the result is this: {"map":[{"k":1,"v":1},{"k":2,"v":2},{"k":3,"v":3}],"obj":[{"k":"a","v":1},{"k":"b","v":2},{"k":"c","v":3}]}`

**Comment by mrbeardad** [comment]
The major problem of this issue is this:
```cpp
std::map<int, int> map{{1, 1}, {2, 2}, {3, 3}};
std::map<std::string, int> obj{{"a", 1}, {"b", 2}, {"c", 3}};
yas::save<yas::file | yas::json>("file", YAS_OBJECT("obj", map, obj);
std::cout << std::ifstream{"file"}.rdbuf();
// OUTPUT:
// {"map":{{"key":1,"val":1},{"key":2,"val":2},{"key":3,"val":3}},"obj":{{"key":"a","val":1.0},{"key":"b","val":2.0},{"key":"c","val":3.0}}}
//
// Desired OUTPUT:
// {"map":{{"key":1,"val":1},{"key":2,"val":2},{"key":3,"val":3}},"obj":{"a":"1","b":2,"c",3}
```
And,
>> Is it different from the latest commit on your local repository?
>
> looks like yes.

the last commit of this repository was pushed on Oct 23, 2020
![image](https://user-images.githubusercontent.com/54128430/104345631-8d79d200-5539-11eb-9a48-9fe17326045a.png)

And I have updated my local YAS repository, and test it again, the result is also `{"map":{{"key":1,"val":1},{"key":2,"val":2},{"key":3,"val":3}},"obj":{{"key":"a","val":1.0},{"key":"b","val":2.0},{"key":"c","val":3.0}}}`. What goes wrong?
