### ISSUE TITLE
The the latest commit which is a PR from askamn/master has broken the bug fix about #93

### ISSUE THREAD

**Issue by mrbeardad** [niXman/yas#94]
When I switch to this commit 627d9e8d66abfaa6e9558296b007f7536fe0e4da and it gives me right json format.  

But the latest commit 45a98550b53c8f766fbc81f42bfb985afc452931 that Merge pull request #91 from askamn/master gives incorrect json format.

So, the the latest commit 45a98550b53c8f766fbc81f42bfb985afc452931  has broken the bug fix about #93 and 627d9e8d66abfaa6e9558296b007f7536fe0e4da

**Comment by niXman** [comment]
it seems that we do not understand each other...

you wrote: `When I switch to this commit 627d9e8 and it gives me right json format.`
ok!

next: `But the latest commit 45a9855 that Merge pull request #91 from askamn/master gives incorrect json format.`
but that commit doesn't make any changes to the file that is the serialization for map: look at diff: https://github.com/niXman/yas/commit/45a98550b53c8f766fbc81f42bfb985afc452931

furthermore, the current `master` branch contains the correct version (https://github.com/niXman/yas/blob/master/include/yas/types/concepts/keyval.hpp) that uses array (`[`, `]`) for maps.
or is it wrong JSON?

**Comment by mrbeardad** [comment]
emmmm.... I have found the reason. That file is different from mine in my local repository, although the hash code of the latest commit in my local repository is same to the remote repository. I've removed  and clone it again, and fixed this problem. Maybe it is a bug about git or github?

**Comment by niXman** [comment]
I shouldn't waste time explaining to you how git works, figure it out yourself.
