### ISSUE TITLE
a question about std:vector

### ISSUE THREAD

**Issue by xujinpeng1117** [niXman/yas#97]
Hello,

When I run the examples\one_func\one_func.pro under qt5.14.2  mingw-32bit, it work fine, but when I comment out 77th line as below, the assert fail. t2 have 6 values after yas::load<flags>(buf, t2); it seems the values are append to std:vector of t2, is my understand correct？ is other containers have similar behavior？

```
int main() {
    type t1, t2;
    t2.i = 0;
    t2.d = 0;
    t2.s.clear();
    //t2.v.clear();

    constexpr std::size_t flags = yas::mem|yas::json;

    auto buf = yas::save<flags>(t1);

    yas::load<flags>(buf, t2);

    // TODO: stackoverflow.com/questions/17333
    assert(t1.i == t2.i && t1.d == t2.d && t1.s == t2.s && t1.v == t2.v);
}
```

jason

**Comment by niXman** [comment]
hi,

>it seems the values are append to std:vector of t2, is my understand correct?

yes.

>is other containers have similar behavior?

yes.
